version: '3.9'
services:
  app:
    build: .
    container_name: resize-server
    image: app
    environment:
      HTTP_PORT: 80
      LOG_LEVEL: 'debug'
      APP_DEFAULT_INTER_FUNC: 'NearestNeighbor'
    ports:
      - "80:8080"
